- API/DataBase/Models/Producto.js
- API/DataBase/Models/Profile.js
- API/DataBase/utils/productID_Generator.js
- README.md
- Profile tiene id custo
- Products tiene id custom
- Profile no tiene mas store_image
> Models finished

- API/.env
- API/.gitignore
- API/DataBase/db.js
- API/Routes/index.js
- API/Routes/storeRoutes.js
- Se importan Operadores de sequelize
- Se crea ruta que trae los registro de profile que no tienen la columna storeName en valor null
- Se deja registro en seeder de profile para prueba de la ruta de traer tiendas.
adjunto pantallazo de prueba
> Get stores

- API/Routes/Controllers/getAllStores.js
- API/Routes/Controllers/stores.js
- API/Routes/storeRoutes.js
-Ruta para filtrar tiendas por storeName en ruta get usando el nombre como parametro de la ruta get.
adjunto pantallazo de prueba
-Logica de rutas de store movida a la carpeta controllers
> Get stores by name

- API/Routes/Controllers/getAllProducts.js
- API/Routes/Controllers/paginado.js
> Controller pagination

- API/Routes/Controllers/getAllProductsByName.js
- API/Routes/productRoutes.js
- Agrega un controlador para buscar por nombre
- Agrega la ruta GET para buscar por nombre, usando querys
> Encontrar productos por nombre

- API/Routes/userRoutes.js
- API/package.json
- Ruta para crear un usuario nuevo.
- Se debe discutir de como vamos a manejar el arreglo de favorites y el arreglo de shoppingCart.
> POST Create User

- API/Routes/userRoutes.js
- Se realiza un Pull Request englobando las rutas get y put para traer y modificar un usuario y asi evitar conflictos entre commits.
> GET and PUT Pull Request correction

- API/DataBase/Models/Profile.js
- API/Routes/Controllers/addProductsToLists.js
- API/Routes/userRoutes.js
- Ruta para agregar a favoritos
- Ruta para agregar a Carrito
- Modificaciones en el controlador para que se pueda usar en ambas rutas
- Modificación en el modelo de Perfil para que favorites y shoppingCart para que su valor default sea un array vacio
> Ruta para agregar productos a Favoritos y al Carrito

- API/Routes/Controllers/deleteProductsOfList.js
- API/Routes/userRoutes.js
- Controlador que deja eliminar productos del carrito o de favoritos
- Ruta para eliminar de favoritos y del carrito
Favoritos antes de eliminar
Favoritos despues de eliminar
Carrito antes de eliminar
Carrito después de eliminar
> Ruta para eliminar favoritos y articulos del carrito

- API/Routes/Controllers/getFilteredProducts.js
- API/Routes/productRoutes.js
- Ruta para realizar todos los filtrados de los productos.
- Es solamente una base para empezar, seguramente se van a ir agregando otros filtrados.
- Use el metodo order tambien para poder ordenar por precio o talle de manera ascendente o descendente. Este metodo order recibe 2 parametros que llegan por query, donde el primero es a traves de que quiero que ordene (precio o talle) y el segundo es como quiero que ordene (asc o desc).
> Ruta para TODOS los filtrados de los productos

- README.md
- Actualizacion de Readme con rutas de tiendas
> readme actualizado con informacion rutas de tiendas

- API/Routes/productRoutes.js
- Se corrige la ruta POST product para poder vincularla con un userID.
> POST product correction

- API/DataBase/Models/Producto.js
- Ahora los productos se agregan a la base de datos en minuscula
> Buscador de productos arreglado

- API/Routes/Controllers/getProductDetail.js
- API/Routes/productRoutes.js
- README.md
- se crea ruta GET /product/id para que se pueda obtener informacion del producto por id
test
cuando encuentra el producto por id
cuando no encuentra el producto por id
> ruta GET obtener detalles de producto por id

- API/Routes/Controllers/getDemographics.js
- API/Routes/Controllers/getSizes.js
- API/Routes/demographicRoutes.js
- API/Routes/index.js
- API/Routes/sizesRoutes.js
- README.md
- Creacion de la ruta GET para traer tallas de ropa
> Ruta GET trae las tallas y demografias de la ropa 

- API/Routes/Controllers/getFilteredProducts.js
- Se corrige el filtrado agregando la opcion de que cuando no le llega ningun filtro a la ruta muestre todos los componentes.
> Filters Correction

- API/DataBase/db.js
- Se cargan url de imagenes para productos de prueba en el seeder
> Urls de imagenes en productos de prueba de los seeders

- API/DataBase/db.js
-Correcion imagen shorts verdes
> Seeders images

- API/Routes/Controllers/getFilteredProducts.js
- Se corrige el filtro por precio para que envie los productos en rangos de precios de 0-25, 0-50, 0-75, etc.
> Filter Price Correction

- API/DataBase/db.js
- API/Routes/Controllers/addReview.js
- API/Routes/productRoutes.js
- API/Routes/userRoutes.js
- README.md
Imagen con un producto con calificación agregada y uno con producto con una calificación agregada
> Seeders cambiados, add review en productos y perfiles, asociaciones cambiadas

- API/Routes/Controllers/addReview.js
- API/Routes/Controllers/getReviewById.js
- API/Routes/Controllers/getReviews.js
- API/Routes/index.js
- API/Routes/productRoutes.js
- API/Routes/reviewRoutes.js
- API/Routes/userRoutes.js
- README.md
- Trae reviews de un perfil
- Trae reviews de un producto
- Trae un review en especifico
- Ahora se manejan los errores cuando se agregan los reviews
Reviews de un perfil
Reviews de un producto
Review por ID
> GET Reviews

- API/Routes/Controllers/avrgScore.js
- API/Routes/productRoutes.js
- API/Routes/userRoutes.js
- README.md
- Hace el promedio de puntaje de todas las reviews de un producto
- Hace el promedio de puntaje de todas las reviews de un perfil
Puntaje en Perfil
Puntaje en Producto
> Avarage Score

- API/Routes/Controllers/login.js
- API/Routes/Utils/getToken.js
- API/Routes/Utils/logger.js
- API/Routes/productRoutes.js
- API/Routes/storeRoutes.js
- API/Routes/userRoutes.js
- README.md
- implementacion de proteccion de ruta cuando no se recibe token en peticion http o es incorrecto no se ejecuta la logica de las rutas enviando un status 401 de no autorizado
- se actualiza readme con rutas que estan protegidas y usuarios de prueba para que sean utilizados en frontend
> Proteccion de rutas POST, PUT y DELETE

- API/Routes/Controllers/putReview.js
- API/Routes/reviewRoutes.js
- README.md
- Ruta que edita una review
- Documentación
Antes y después de editar una review
> PUT reviews

- API/Routes/userRoutes.js
-Se agrega parametro username de ruta de creacion de usuarios
> Agrega parametro username a ruta de creacion de usuarios

- API/Routes/Controllers/getFilteredProducts.js
- API/Routes/productRoutes.js
- README.md
- Agregado de filtro por color y name, y vinculo entre todos.
> Add Filters

- API/Routes/Controllers/getFilteredProducts.js
- API/Routes/productRoutes.js
- Se corrige el paginado trabajandolo desde el back.
> Paginated correction

- API/Routes/Controllers/getFilteredProducts.js
- API/Routes/productRoutes.js
- Se agrega ordenamiento por precio y nombre de forma asc o desc.
> Orders by price and name ASC or DESC

- API/.gitignore
- API/Routes/userRoutes.js
- README.md
- se modifica la ruta GET /user/get/:id a POST /user/get para solicitar informacion del usuario con el token de sesion
> Cambio de ruta informacion profile de get a post

- API/app.js
- Se actualizan politicas cors para que permitan recibir peticions http con header de autorizacion del frontend
> actualizan politicas de cors para aceptar encabezados de autorizacion en peticiones http

- README.md
- Routes/Controllers/getShoppingcart.js
- Routes/userRoutes.js
- Ruta que traer los productos del carrito de compras
- Documentación
> GET productos del carrito

- Routes/Controllers/getFavoritesList.js
- Routes/userRoutes.js
- Se crea la ruta para traer los productos agregados a favoritos de un usuario.
> GET favorites products

- DataBase/Models/Profile.js
- Routes/Utils/cloudinary.js
- Routes/Utils/imageUploader.js
- Routes/Utils/multer.js
- Routes/index.js
- Routes/productRoutes.js
- Routes/userRoutes.js
- package.json
- Instalado extension cloudinary
- Instalado extension multer
- Agregado archivo que configura el cloudinary en utils
- Agregado archivo que configura el middleware de multer en utils
- Agregado archivo "imageUploader" que permite subir imagenes devolviendo una url de la imagen subida
- Agregado los middlewares
- POST de producto actualizado para subir imagenes 
- POST de producto actualizado para subir fotos de perfil y banner
- Nuevas variables en .env, CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET. Estas son necesarias para conectarse con Cloudinary
POST de usuario
Se añade a la base de datos con las urls de la imagen de perfil y el banner
Se agrega a cloudinary
Ademas en caso de que no se mande ninguna foto de perfil, se pondra uno por defecto
> Subida de imágenes a Cloudinary

- README.md
- Routes/Controllers/getVariant.js
- Routes/index.js
- Routes/variantRoutes.js
- Ruta traer una variante especifica por id
> GET variant

- README.md
- Routes/Controllers/deleteVariant.js
- Routes/Controllers/putVariant.js
- Routes/variantRoutes.js
- Ruta para eliminar variantes
- Ruta para modificar variantes
- Documentación
> DELETE y PUT de variantes

- README.md
- Routes/Controllers/addProduct.js
- Routes/productRoutes.js
- Nueva función en controladores para el POST
- Ahora se pasan variantes para el producto
- Se agrega una imagen
- Mejores manejo de errores
- Documentación faltante agregada
POST request
Resultado
> POST de productos actulizado

- DataBase/Models/Producto.js
- DataBase/Models/Profile.js
- README.md
- Routes/Controllers/activateProduct.js
- Routes/Controllers/activateProfile.js
- Routes/Controllers/deActivateProduct.js
- Routes/Controllers/deActivateProfile.js
- Routes/activateRoutes.js
- Routes/index.js
- Modelos de perfil y producto ahora tienen un parámetro booleano de isActive, por default esta estan activados
- Ruta para activar perfil
- Ruta para desactivar perfil
- Ruta para activar producto
- Ruta para desactivar producto
- Documentación
> Activacion y Desactivacion de Perfiles y Productos

- Routes/Controllers/getAllMarketedProducts.js
- Routes/Controllers/getMarketedProductDetail.js
- Routes/index.js
- Routes/marketedRoutes.js
- Se creo la ruta para traer todos los productos vendidos.
- Se creo la ruta para traer el detalle de un producto vendido.
> GET historial de ventas y detalle de un producto vendido

- Routes/Controllers/getFilteredProducts.js
- Se corrigen todos los filtros teniendo en cuenta la tabla variant.
> Filters correction with variant

- Routes/marketedRoutes.js
- Se corrige la exportacion de la ruta marketedRoutes
> MarketedRoutes export correction

- Routes/marketedRoutes.js
- Se corrigen las rutas MarketedRoutes.
> MarketedRoutes Correction

- README.md
- Routes/Controllers/stores.js
- Routes/storeRoutes.js
- se arregla y modifica ruta para obtener tienda por nombre para que se pueda buscar con las primeras letras y con query en la url 
- se actualiza readme
> Fix store name

- Routes/Controllers/getFavoritesList.js
- Routes/Controllers/getShoppingcart.js
Ahora los get de favoritos y del carrito si traeran todos los elementos aunque esten repetidos
> GET favorites y shopppingcart FIX

- DataBase/Models/Producto.js
- DataBase/Seeders/products.js
- README.md
- Routes/Controllers/addProduct.js
- Routes/index.js
- Modelo del producto modificado para que image sea un array de texto
- Ruta para añadir productos modificada
- Seeders modificados
Request
Resultados
> Añadir mas imagenes al Producto

- README.md
- Routes/Controllers/patchProduct.js
- Routes/Controllers/patchProfile.js
- Routes/productRoutes.js
- Routes/userRoutes.js
- Ruta PATCH para modificar usuario
- Ruta PATCH para modificar producto
- Ambas rutas con proteccion
> Rutas para modificar productos y usuarios

- Routes/Controllers/deleteProductsOfList.js
- app.js
- Se mejora la configuracion de mercado pago.
> MercadoPago Correction

- README.md
- Routes/Controllers/getShoppingcart.js
- Ahora al traer los items del carrito este viene con la talla y color seleccionados
- Ahora se agregan el id de la variantes y no de los productos al carrito
Resultado Final:
> GET de carrito actualizado

- DataBase/Models/Profile.js
- README.md
- Routes/Controllers/activateModerator.js
- Routes/activateRoutes.js
- Agregar el atributo isModerator al perfil
- Ruta PUT que modifica un perfil para darle el rol de moderador (ruta no esta protegida)
> Rol de moderador

- Routes/Controllers/postMarketedProducts.js
- Routes/marketedRoutes.js
- app.js
- Se agrega la ruta postMarketedProduct para poder postear productos comprados a la tabla marketedProduct.
> postMarketedProduct

- README.md
- Routes/Controllers/variantsStock.js
- Routes/variantRoutes.js
- Ruta que permite añadir o eliminar stock
> Añade o elimina el Stock de una variante

- DataBase/Models/MarketedProduct.js
- Routes/Controllers/postMarketedProducts.js
-Se modifica la tabla marketedProduct segun las nuevas modificaciones de las propeidades de los productos agregados al carrito.
> Modificacion tabla marketedProduct

- DataBase/Models/MarketedProduct.js
- README.md
- Routes/Controllers/postMarketedProducts.js
- Routes/userRoutes.js
- Ruta post que crea un registro de compra con los datos del carrito y ademas resta en 1 el stock de la variante comprada (no tiene proteccion)
- Cambios a la tabla de MarketedProduct
> Flow de Venta y Compra

- README.md
- Routes/authRoutes.js
- package.json
Backend
- se crean rutas de recuperacion de password una para enviar email, otra para setear nueva password y una ruta put para modificar la password
- se instala dependencia nodemailer
- se crean dos variables de entorno para conectar backend con servicio de email de gmail una direccion de email y password ( se dejaran en el chat de backend de discord )
Frontend
- se crean dos componentes uno de olvido de password y otro de crear nueva password
Flujo 
se tiene un usuario
se da clic en el link de olvido su contrasena
se redirecciona a un enlace que recibe una direccion de email
se recibira un email con un enlace unico para que el usuario cambie su password
se entra al enlace y se cambia una nueva password
se redirecciona a la pantalla de login
y se inicia sesion con nuevas credenciales
> Recuperacion de password

- Auth/GoogleSSO.js
- DataBase/Models/Profile.js
- DataBase/Seeders/users.js
- README.md
- Routes/authRoutes.js
- Routes/userRoutes.js
Backend
- Se crea nuevo campo verified en el model de profiles
- Se crean rutas para manejar el proceso de verficacion de cuenta de usuario
Frontend
- Se crea componente para verificacion de cuenta y para cuando falla la verificacion
Flujo Verificacion de cuenta
Se Crea el usuario con campo verificacion con valor false
Se envia el correo de verificacion
Se ingresa al link del mensaje de verificacion
- En caso de ser exitosa se modifica el campo verified en el modelo de profiles al valor true al momento de hacer click en el enlace y te redirecciona a la pagina principal del ecommerce
- En caso de fallar la verificacion te redirige a un enlace para reenviar el correo de confirmacion
> Proceso de verificacion de cuenta

- README.md
- Routes/Controllers/getSelledProducts.js
- Routes/userRoutes.js
- Esta ruta trae todos los productos vendidos de un perfil
> GET Ventas

- Routes/authRoutes.js
- Se crea una nueva ruta para que el mensaje del mail a la hora de la compra sea diferente para el comprador y el vendedor.
> Correccion de envio de mail al comprar

- Routes/Controllers/addReview.js
- Routes/productRoutes.js
- Routes/userRoutes.js
Backend
- Se modifica ruta y funcion para que se agrege el profileId del token desencriptado para la autenticacion de la review
Frontend
- Se adjusta action para postear review en el backend y limpiar la caja de review
- Se llama historial de compra en componente home
- Se oculta checkbox recuerdame en el login
Flujo de postear review
agregar producto al carrito
se compra el producto
se ingresa al detalle del producto para escribir la review
se envia la review y se vacia el componente review
se observa que la review queda almacenada en la tabla qualifications
> Habilitacion de accion de postear Reviews

- README.md
- Routes/Controllers/getEstadistics.js
- Routes/Controllers/getSelledProducts.js
- Routes/storeRoutes.js
- Routes/userRoutes.js
- Ruta que trae datos especificos de cada compra
> GET estadisticas

- README.md
- Routes/Controllers/getOnSell.js
- Routes/userRoutes.js
- Ruta que trae todos los productos en venta de un perfil en especifico
> GET productos en venta

- README.md
- Routes/Controllers/patchProfile.js
- Routes/userRoutes.js
- index.js
- Se modifica ruta para modificar perfil del usuario con funcionalidad para subir imagenes a cloudinary del banner y foto de perfil
- Se dejan variables de entorno de la cuenta de cloudinary con la que se realizan pruebas de los cambios de este pull en el chat general de discord
la nueva ruta POST /user/update
> Implementacion de subir imagenes a cloudinary

- index.js
- Este pull se realiza para dejar la configuracion de force en true
> set force true

- Routes/Controllers/getFilteredProducts.js
- Routes/productRoutes.js
- Se implementa query de sequilize para arreglar problemas con filtro de precios
> Fix bug filtros de precios
